<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<div class="container">  
    <div class="row">
        <div class="col-lg-12 col-md-12">   
            
            <?php
            $form = $this->form;
            $form->prepare();
            $form->setAttribute('action', $this->baseUrl().'/users/index/login-process');
            $form->setAttribute('method', 'post');

            $formLabel = $this->plugin('formLabel');

            echo $this->form()->openTag($form);
            ?>
            <div class="form_element">
            <?php
                $userId = $form->get('userId');
                echo $formLabel->openTag() . $userId->getOption('label');
                echo $this->formInput($userId);
                echo $this->formElementErrors($userId);
                echo $formLabel->closeTag();
            ?>
            </div>

            <div class="form_element">
            <?php
                $password = $form->get('password');
                echo $formLabel->openTag() . $password->getOption('label');
                echo $this->formInput($password);
                echo $this->formElementErrors($password);
                echo $formLabel->closeTag();
            ?>
            </div>

            <div class="form_element">
            <?php
                $submit = $form->get('submit');
                echo $this->formInput($submit);
            ?>
            </div>
            <?php echo $this->form()->closeTag() ?>



        </div>
    </div>
</div>