<div class="content-wrapper">
    <section class="content-header">
        <h1>
            Page Header
            <small>Optional description</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Level</a></li>
            <li class="active">Here</li>
        </ol>
    </section>
    
    <section class="content">
    <?php
    $form = $this->form;
    $form->prepare();
    $form->setAttribute('action', 'login');
    $form->setAttribute('method', 'post');

    $formLabel = $this->plugin('formLabel');

    echo $this->form()->openTag($form);
    ?>
        <div class="form_element">
        <?php
            $userId = $form->get('userId');
            echo $formLabel->openTag() . $userId->getOption('label');
            echo $this->formInput($userId);
            echo $this->formElementErrors($userId);
            echo $formLabel->closeTag();
        ?>
        </div>

        <div class="form_element">
        <?php
            $password = $form->get('password');
            echo $formLabel->openTag() . $password->getOption('label');
            echo $this->formInput($password);
            echo $this->formElementErrors($password);
            echo $formLabel->closeTag();
        ?>
        </div>
        
        <div class="form_element">
        <?php
            $submit = $form->get('submit');
            echo $this->formInput($submit);
        ?>
        </div>

        <?php echo $this->form()->closeTag() ?>
      
    </section>
  </div>
  

