<?php echo $this->doctype(); ?>

<html lang="en">
  <head>
    <?php
    echo $this->headTitle(''. $this->translate('School Management'))->setSeparator(' - ')->setAutoEscape(false);

    echo $this->headMeta()
        ->setCharset('UTF-8')
        ->appendName('viewport', 'width=device-width, initial-scale=1')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');
    
    echo $this->headScript()
    ->appendFile($this->baseUrl().'/js/jquery.min.js');

    
    echo $this->headLink()   
        ->prependStylesheet($this->baseUrl().'/css/bootstrap.min.css')
        ->prependStylesheet($this->baseUrl().'/css/font-awesome.min.css')
        ->prependStylesheet($this->baseUrl().'/css/superslides.css')             
        ->prependStylesheet($this->baseUrl().'/css/slick.css')
        ->prependStylesheet($this->baseUrl().'/css/jquery.circliful.css')
        ->prependStylesheet($this->baseUrl().'/css/animate.css')             
        ->prependStylesheet($this->baseUrl().'/css/jquery.tosrus.all.css')
        ->prependStylesheet($this->baseUrl().'/css/themes/default-theme.css')            
        ->prependStylesheet($this->baseUrl().'/style.css');
    ?>
  </head>
  <body>        
    <?php echo $this->partial('header'); ?>
    <div class="container">
        <?php echo $this->content; ?>
    </div>   
    <?php echo $this->partial('footer'); ?>
      
  </body>
</html>


<?php 
    echo $this->headScript()    
    ->prependFile($this->baseUrl().'/js/wow.min.js')
    ->prependFile($this->baseUrl().'/js/bootstrap.min.js')
    ->prependFile($this->baseUrl().'/js/slick.min.js')
    ->prependFile($this->baseUrl().'/js/jquery.easing.1.3.js')
    ->prependFile($this->baseUrl().'/js/jquery.animate-enhanced.min.js')
    ->prependFile($this->baseUrl().'/js/jquery.superslides.min.js')
    ->prependFile($this->baseUrl().'/js/jquery.circliful.min.js')
    ->prependFile($this->baseUrl().'/js/jquery.tosrus.min.all.js')
    ->prependFile($this->baseUrl().'/js/custom.js')          
    ->prependFile($this->baseUrl().'/js/html5shiv.min.js', 'text/javascript', array('conditional' => 'lt IE 9'))
    ->prependFile($this->baseUrl().'/js/respond.min.js',   'text/javascript', array('conditional' => 'lt IE 9'));         
?>