<?php echo $this->doctype(); ?>

<html lang="en">
  <head>
    <?php
    echo $this->headTitle(''. $this->translate('School Management'))->setSeparator(' - ')->setAutoEscape(false);

    echo $this->headMeta()
        ->setCharset('UTF-8')
        ->appendName('viewport', 'width=device-width, initial-scale=1')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');
    
    echo $this->headScript()
    ->prependFile('https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js')   
    ->prependFile($this->basePath('js/html5shiv.min.js'), 'text/javascript', array('conditional' => 'lt IE 9'))
    ->prependFile($this->basePath('js/respond.min.js'),   'text/javascript', array('conditional' => 'lt IE 9')); 
    
    

    echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ->prependStylesheet($this->basePath('css/font-awesome.min.css'))
        ->prependStylesheet($this->basePath('css/superslides.css'))             
        ->prependStylesheet($this->basePath('css/slick.css'))
        ->prependStylesheet($this->basePath('css/jquery.circliful.css'))
        ->prependStylesheet($this->basePath('css/animate.css'))             
        //->prependStylesheet($this->basePath('css/queryLoader.css'))
        ->prependStylesheet($this->basePath('css/jquery.tosrus.all.css'))
        ->prependStylesheet($this->basePath('css/themes/default-theme.css'))            
        ->prependStylesheet($this->basePath('style.css'))            
        ->prependStylesheet('http://fonts.googleapis.com/css?family=Merriweather')
        ->prependStylesheet('http://fonts.googleapis.com/css?family=Varela');
    ?>
  </head>
  <body>  

    <?php echo $this->partial('header'); ?>
    <div class="container">
        <?php echo $this->content; ?>
    </div>   
    <?php echo $this->partial('footer'); ?>
      
  </body>
</html>


<?php 
    echo $this->headScript()
    ->prependFile($this->basePath('js/jquery.min.js'))
    ->prependFile($this->basePath('js/queryloader2.min.js'))
    ->prependFile($this->basePath('js/wow.min.js'))
    ->prependFile($this->basePath('js/bootstrap.min.js'))
    ->prependFile($this->basePath('js/slick.min.js'))
    ->prependFile($this->basePath('js/jquery.easing.1.3.js'))
    ->prependFile($this->basePath('js/jquery.animate-enhanced.min.js'))
    ->prependFile($this->basePath('js/jquery.superslides.min.js'))
    ->prependFile($this->basePath('js/jquery.circliful.min.js'))
    ->prependFile($this->basePath('js/jquery.tosrus.min.all.js'))
    ->prependFile($this->basePath('js/custom.js'))          
    ->prependFile($this->basePath('js/html5shiv.min.js'), 'text/javascript', array('conditional' => 'lt IE 9'))
    ->prependFile($this->basePath('js/respond.min.js'),   'text/javascript', array('conditional' => 'lt IE 9')); 
?>